name: example_bps_sso
description: "Flutter project to showcase bps sso app."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0

environment:
  sdk: ^3.9.2

dependencies:
  alice: ^1.0.0
  alice_dio: ^1.0.2
  app_links: ^6.3.2
  auto_route: ^10.1.2
  bps_sso_sdk:
    path: ../.

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.1.1
  injectable: ^2.4.4
  path: ^1.9.0
  path_provider: ^2.1.4
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.4.13

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
