name: bps_sso_sdk
description: A Flutter SDK for BPS (Badan Pusat Statistik) SSO authentication integration
version: 1.4.0
homepage: https://github.com/IPDS-59/bps_sso_flutter_sdk
repository: https://github.com/IPDS-59/bps_sso_flutter_sdk

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

platforms:
  android:
  ios:

dependencies:
  crypto: ^3.0.7
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.4.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
